// Code generated by "stringer -type=NodeType -output stringer_generated.go"; DO NOT EDIT.

package nflex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Slice-1]
	_ = x[Nil-2]
	_ = x[String-3]
	_ = x[Float-4]
	_ = x[Int-5]
	_ = x[Bool-6]
	_ = x[Map-7]
}

const _NodeType_name = "UndefinedSliceNilStringFloatIntBoolMap"

var _NodeType_index = [...]uint8{0, 9, 14, 17, 23, 28, 31, 35, 38}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
